env:
  global:
    - BRANCH=v1.1.0

sudo: true

install:
  - curl -sLo - http://j.mp/install-travis-docker | sh -xe

language: scala

scala:
 - 2.11.7

jdk:
  - oraclejdk8

script:
  - ./run 'sbt test'